-- CreateTable
CREATE TABLE "capex_items" (
    "id" SERIAL NOT NULL,
    "clientName" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "subCategory" TEXT NOT NULL,
    "typeOfExpense" TEXT NOT NULL,
    "billing" TEXT,
    "warehouseCode" TEXT,
    "billingMethod" TEXT NOT NULL,
    "glName" TEXT,
    "assetLife" INTEGER NOT NULL,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3),
    "intOnCapexAnnual" DECIMAL(10,4) NOT NULL,
    "uom" TEXT,
    "unitCost" DECIMAL(14,2) NOT NULL,
    "qty" DECIMAL(14,4) NOT NULL,
    "contingentPct" DECIMAL(10,4),
    "managementFeePct" DECIMAL(10,4),
    "billingMonth" TIMESTAMP(3) NOT NULL,
    "intOnCapexMonthly" DECIMAL(14,6) NOT NULL,
    "investmentValue" DECIMAL(16,2) NOT NULL,
    "usedLife" DECIMAL(14,4) NOT NULL,
    "amortPerMonth" DECIMAL(16,4) NOT NULL,
    "capexBillingStd" DECIMAL(16,4) NOT NULL,
    "capexBillingRed" DECIMAL(16,4) NOT NULL,
    "maintenance" DECIMAL(16,4) NOT NULL,
    "aggregateCost" DECIMAL(16,4) NOT NULL,
    "contingencyCost" DECIMAL(16,4) NOT NULL,
    "managementFeeInr" DECIMAL(16,4) NOT NULL,
    "totalBill" DECIMAL(16,4) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "capex_items_pkey" PRIMARY KEY ("id")
);
